version: '3'
services:
  user-service:
    container_name: luffle-ecommerce-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8150:8080"
    restart: always
    entrypoint: java -jar -Dspring.profiles.active=prod app.jar
